export interface StateDistrict {
  code: string;
  name: string;
  districts: { code: string; name: string }[];
}

export const indianStates: StateDistrict[] = [
  {
    code: "AN",
    name: "Andaman and Nicobar Islands",
    districts: [
      { code: "01", name: "Nicobar" },
      { code: "02", name: "North and Middle Andaman" },
      { code: "03", name: "South Andaman" },
    ],
  },
  {
    code: "AP",
    name: "Andhra Pradesh",
    districts: [
      { code: "01", name: "Anantapur" },
      { code: "02", name: "Chittoor" },
      { code: "03", name: "East Godavari" },
      { code: "04", name: "Guntur" },
      { code: "05", name: "Krishna" },
      { code: "06", name: "Kurnool" },
      { code: "07", name: "Nellore" },
      { code: "08", name: "Prakasam" },
      { code: "09", name: "Srikakulam" },
      { code: "10", name: "Visakhapatnam" },
      { code: "11", name: "Vizianagaram" },
      { code: "12", name: "West Godavari" },
      { code: "13", name: "YSR Kadapa" },
    ],
  },
  {
    code: "AR",
    name: "Arunachal Pradesh",
    districts: [
      { code: "01", name: "Anjaw" },
      { code: "02", name: "Changlang" },
      { code: "03", name: "East Kameng" },
      { code: "04", name: "East Siang" },
      { code: "05", name: "Itanagar Capital Complex" },
      { code: "06", name: "Lohit" },
      { code: "07", name: "Papum Pare" },
      { code: "08", name: "Tawang" },
      { code: "09", name: "Tirap" },
      { code: "10", name: "West Kameng" },
      { code: "11", name: "West Siang" },
    ],
  },
  {
    code: "AS",
    name: "Assam",
    districts: [
      { code: "01", name: "Baksa" },
      { code: "02", name: "Barpeta" },
      { code: "03", name: "Cachar" },
      { code: "04", name: "Darrang" },
      { code: "05", name: "Dibrugarh" },
      { code: "06", name: "Goalpara" },
      { code: "07", name: "Guwahati" },
      { code: "08", name: "Jorhat" },
      { code: "09", name: "Kamrup" },
      { code: "10", name: "Nagaon" },
      { code: "11", name: "Sivasagar" },
      { code: "12", name: "Tinsukia" },
    ],
  },
  {
    code: "BR",
    name: "Bihar",
    districts: [
      { code: "01", name: "Araria" },
      { code: "02", name: "Aurangabad" },
      { code: "03", name: "Begusarai" },
      { code: "04", name: "Bhagalpur" },
      { code: "05", name: "Darbhanga" },
      { code: "06", name: "Gaya" },
      { code: "07", name: "Muzaffarpur" },
      { code: "08", name: "Nalanda" },
      { code: "09", name: "Patna" },
      { code: "10", name: "Purnia" },
      { code: "11", name: "Saharsa" },
      { code: "12", name: "Vaishali" },
    ],
  },
  {
    code: "CH",
    name: "Chandigarh",
    districts: [
      { code: "01", name: "Chandigarh" },
    ],
  },
  {
    code: "CG",
    name: "Chhattisgarh",
    districts: [
      { code: "01", name: "Bastar" },
      { code: "02", name: "Bilaspur" },
      { code: "03", name: "Durg" },
      { code: "04", name: "Korba" },
      { code: "05", name: "Raipur" },
      { code: "06", name: "Rajnandgaon" },
      { code: "07", name: "Surguja" },
    ],
  },
  {
    code: "DN",
    name: "Dadra and Nagar Haveli and Daman and Diu",
    districts: [
      { code: "01", name: "Dadra and Nagar Haveli" },
      { code: "02", name: "Daman" },
      { code: "03", name: "Diu" },
    ],
  },
  {
    code: "DL",
    name: "Delhi",
    districts: [
      { code: "01", name: "Central Delhi" },
      { code: "02", name: "East Delhi" },
      { code: "03", name: "New Delhi" },
      { code: "04", name: "North Delhi" },
      { code: "05", name: "North East Delhi" },
      { code: "06", name: "North West Delhi" },
      { code: "07", name: "Shahdara" },
      { code: "08", name: "South Delhi" },
      { code: "09", name: "South East Delhi" },
      { code: "10", name: "South West Delhi" },
      { code: "11", name: "West Delhi" },
    ],
  },
  {
    code: "GA",
    name: "Goa",
    districts: [
      { code: "01", name: "North Goa" },
      { code: "02", name: "South Goa" },
    ],
  },
  {
    code: "GJ",
    name: "Gujarat",
    districts: [
      { code: "01", name: "Ahmedabad" },
      { code: "02", name: "Amreli" },
      { code: "03", name: "Anand" },
      { code: "04", name: "Banaskantha" },
      { code: "05", name: "Bharuch" },
      { code: "06", name: "Bhavnagar" },
      { code: "07", name: "Gandhinagar" },
      { code: "08", name: "Jamnagar" },
      { code: "09", name: "Kutch" },
      { code: "10", name: "Mehsana" },
      { code: "11", name: "Rajkot" },
      { code: "12", name: "Surat" },
      { code: "13", name: "Vadodara" },
    ],
  },
  {
    code: "HR",
    name: "Haryana",
    districts: [
      { code: "01", name: "Ambala" },
      { code: "02", name: "Bhiwani" },
      { code: "03", name: "Faridabad" },
      { code: "04", name: "Gurugram" },
      { code: "05", name: "Hisar" },
      { code: "06", name: "Karnal" },
      { code: "07", name: "Kurukshetra" },
      { code: "08", name: "Panipat" },
      { code: "09", name: "Rohtak" },
      { code: "10", name: "Sonipat" },
    ],
  },
  {
    code: "HP",
    name: "Himachal Pradesh",
    districts: [
      { code: "01", name: "Bilaspur" },
      { code: "02", name: "Chamba" },
      { code: "03", name: "Hamirpur" },
      { code: "04", name: "Kangra" },
      { code: "05", name: "Kullu" },
      { code: "06", name: "Mandi" },
      { code: "07", name: "Shimla" },
      { code: "08", name: "Solan" },
      { code: "09", name: "Una" },
    ],
  },
  {
    code: "JK",
    name: "Jammu and Kashmir",
    districts: [
      { code: "01", name: "Anantnag" },
      { code: "02", name: "Baramulla" },
      { code: "03", name: "Jammu" },
      { code: "04", name: "Kathua" },
      { code: "05", name: "Pulwama" },
      { code: "06", name: "Rajouri" },
      { code: "07", name: "Srinagar" },
      { code: "08", name: "Udhampur" },
    ],
  },
  {
    code: "JH",
    name: "Jharkhand",
    districts: [
      { code: "01", name: "Bokaro" },
      { code: "02", name: "Dhanbad" },
      { code: "03", name: "Dumka" },
      { code: "04", name: "East Singhbhum" },
      { code: "05", name: "Giridih" },
      { code: "06", name: "Hazaribagh" },
      { code: "07", name: "Ranchi" },
      { code: "08", name: "West Singhbhum" },
    ],
  },
  {
    code: "KA",
    name: "Karnataka",
    districts: [
      { code: "01", name: "Bagalkot" },
      { code: "02", name: "Ballari" },
      { code: "03", name: "Belagavi" },
      { code: "04", name: "Bengaluru Rural" },
      { code: "05", name: "Bengaluru Urban" },
      { code: "06", name: "Dakshina Kannada" },
      { code: "07", name: "Dharwad" },
      { code: "08", name: "Hassan" },
      { code: "09", name: "Kalaburagi" },
      { code: "10", name: "Mangaluru" },
      { code: "11", name: "Mysuru" },
      { code: "12", name: "Shivamogga" },
      { code: "13", name: "Tumakuru" },
      { code: "14", name: "Udupi" },
    ],
  },
  {
    code: "KL",
    name: "Kerala",
    districts: [
      { code: "01", name: "Alappuzha" },
      { code: "02", name: "Ernakulam" },
      { code: "03", name: "Idukki" },
      { code: "04", name: "Kannur" },
      { code: "05", name: "Kasaragod" },
      { code: "06", name: "Kollam" },
      { code: "07", name: "Kottayam" },
      { code: "08", name: "Kozhikode" },
      { code: "09", name: "Malappuram" },
      { code: "10", name: "Palakkad" },
      { code: "11", name: "Pathanamthitta" },
      { code: "12", name: "Thiruvananthapuram" },
      { code: "13", name: "Thrissur" },
      { code: "14", name: "Wayanad" },
    ],
  },
  {
    code: "LA",
    name: "Ladakh",
    districts: [
      { code: "01", name: "Kargil" },
      { code: "02", name: "Leh" },
    ],
  },
  {
    code: "LD",
    name: "Lakshadweep",
    districts: [
      { code: "01", name: "Lakshadweep" },
    ],
  },
  {
    code: "MP",
    name: "Madhya Pradesh",
    districts: [
      { code: "01", name: "Bhopal" },
      { code: "02", name: "Gwalior" },
      { code: "03", name: "Indore" },
      { code: "04", name: "Jabalpur" },
      { code: "05", name: "Rewa" },
      { code: "06", name: "Sagar" },
      { code: "07", name: "Satna" },
      { code: "08", name: "Ujjain" },
    ],
  },
  {
    code: "MH",
    name: "Maharashtra",
    districts: [
      { code: "01", name: "Ahmednagar" },
      { code: "02", name: "Aurangabad" },
      { code: "03", name: "Kolhapur" },
      { code: "04", name: "Mumbai City" },
      { code: "05", name: "Mumbai Suburban" },
      { code: "06", name: "Nagpur" },
      { code: "07", name: "Nashik" },
      { code: "08", name: "Pune" },
      { code: "09", name: "Ratnagiri" },
      { code: "10", name: "Satara" },
      { code: "11", name: "Solapur" },
      { code: "12", name: "Thane" },
    ],
  },
  {
    code: "MN",
    name: "Manipur",
    districts: [
      { code: "01", name: "Bishnupur" },
      { code: "02", name: "Churachandpur" },
      { code: "03", name: "Imphal East" },
      { code: "04", name: "Imphal West" },
      { code: "05", name: "Thoubal" },
    ],
  },
  {
    code: "ML",
    name: "Meghalaya",
    districts: [
      { code: "01", name: "East Garo Hills" },
      { code: "02", name: "East Jaintia Hills" },
      { code: "03", name: "East Khasi Hills" },
      { code: "04", name: "Ri-Bhoi" },
      { code: "05", name: "Shillong" },
      { code: "06", name: "West Garo Hills" },
      { code: "07", name: "West Khasi Hills" },
    ],
  },
  {
    code: "MZ",
    name: "Mizoram",
    districts: [
      { code: "01", name: "Aizawl" },
      { code: "02", name: "Champhai" },
      { code: "03", name: "Kolasib" },
      { code: "04", name: "Lawngtlai" },
      { code: "05", name: "Lunglei" },
      { code: "06", name: "Serchhip" },
    ],
  },
  {
    code: "NL",
    name: "Nagaland",
    districts: [
      { code: "01", name: "Dimapur" },
      { code: "02", name: "Kohima" },
      { code: "03", name: "Mokokchung" },
      { code: "04", name: "Mon" },
      { code: "05", name: "Tuensang" },
      { code: "06", name: "Wokha" },
    ],
  },
  {
    code: "OD",
    name: "Odisha",
    districts: [
      { code: "01", name: "Balasore" },
      { code: "02", name: "Bhubaneswar" },
      { code: "03", name: "Cuttack" },
      { code: "04", name: "Ganjam" },
      { code: "05", name: "Kendujhar" },
      { code: "06", name: "Khordha" },
      { code: "07", name: "Puri" },
      { code: "08", name: "Sambalpur" },
    ],
  },
  {
    code: "PY",
    name: "Puducherry",
    districts: [
      { code: "01", name: "Karaikal" },
      { code: "02", name: "Mahe" },
      { code: "03", name: "Puducherry" },
      { code: "04", name: "Yanam" },
    ],
  },
  {
    code: "PB",
    name: "Punjab",
    districts: [
      { code: "01", name: "Amritsar" },
      { code: "02", name: "Bathinda" },
      { code: "03", name: "Jalandhar" },
      { code: "04", name: "Ludhiana" },
      { code: "05", name: "Mohali" },
      { code: "06", name: "Patiala" },
      { code: "07", name: "Pathankot" },
    ],
  },
  {
    code: "RJ",
    name: "Rajasthan",
    districts: [
      { code: "01", name: "Ajmer" },
      { code: "02", name: "Alwar" },
      { code: "03", name: "Bikaner" },
      { code: "04", name: "Jaipur" },
      { code: "05", name: "Jodhpur" },
      { code: "06", name: "Kota" },
      { code: "07", name: "Udaipur" },
    ],
  },
  {
    code: "SK",
    name: "Sikkim",
    districts: [
      { code: "01", name: "East Sikkim" },
      { code: "02", name: "North Sikkim" },
      { code: "03", name: "South Sikkim" },
      { code: "04", name: "West Sikkim" },
    ],
  },
  {
    code: "TN",
    name: "Tamil Nadu",
    districts: [
      { code: "01", name: "Chennai" },
      { code: "02", name: "Coimbatore" },
      { code: "03", name: "Erode" },
      { code: "04", name: "Kanchipuram" },
      { code: "05", name: "Madurai" },
      { code: "06", name: "Salem" },
      { code: "07", name: "Thanjavur" },
      { code: "08", name: "Tiruchirappalli" },
      { code: "09", name: "Tirunelveli" },
      { code: "10", name: "Vellore" },
    ],
  },
  {
    code: "TS",
    name: "Telangana",
    districts: [
      { code: "01", name: "Adilabad" },
      { code: "02", name: "Hyderabad" },
      { code: "03", name: "Karimnagar" },
      { code: "04", name: "Khammam" },
      { code: "05", name: "Medak" },
      { code: "06", name: "Nalgonda" },
      { code: "07", name: "Nizamabad" },
      { code: "08", name: "Rangareddy" },
      { code: "09", name: "Warangal" },
    ],
  },
  {
    code: "TR",
    name: "Tripura",
    districts: [
      { code: "01", name: "Agartala" },
      { code: "02", name: "Dhalai" },
      { code: "03", name: "North Tripura" },
      { code: "04", name: "South Tripura" },
      { code: "05", name: "West Tripura" },
    ],
  },
  {
    code: "UP",
    name: "Uttar Pradesh",
    districts: [
      { code: "01", name: "Agra" },
      { code: "02", name: "Aligarh" },
      { code: "03", name: "Allahabad (Prayagraj)" },
      { code: "04", name: "Bareilly" },
      { code: "05", name: "Ghaziabad" },
      { code: "06", name: "Gorakhpur" },
      { code: "07", name: "Kanpur" },
      { code: "08", name: "Lucknow" },
      { code: "09", name: "Meerut" },
      { code: "10", name: "Moradabad" },
      { code: "11", name: "Noida" },
      { code: "12", name: "Varanasi" },
    ],
  },
  {
    code: "UK",
    name: "Uttarakhand",
    districts: [
      { code: "01", name: "Almora" },
      { code: "02", name: "Chamoli" },
      { code: "03", name: "Dehradun" },
      { code: "04", name: "Haridwar" },
      { code: "05", name: "Nainital" },
      { code: "06", name: "Pauri Garhwal" },
      { code: "07", name: "Udham Singh Nagar" },
    ],
  },
  {
    code: "WB",
    name: "West Bengal",
    districts: [
      { code: "01", name: "Bankura" },
      { code: "02", name: "Bardhaman" },
      { code: "03", name: "Darjeeling" },
      { code: "04", name: "Hooghly" },
      { code: "05", name: "Howrah" },
      { code: "06", name: "Kolkata" },
      { code: "07", name: "Malda" },
      { code: "08", name: "Murshidabad" },
      { code: "09", name: "Nadia" },
      { code: "10", name: "North 24 Parganas" },
      { code: "11", name: "South 24 Parganas" },
    ],
  },
];


export const indianCities = [
  "Mumbai", "Delhi", "Bengaluru", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Pune",
  "Jaipur", "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam",
  "Patna", "Vadodara", "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Ranchi", "Faridabad",
  "Meerut", "Rajkot", "Varanasi", "Srinagar", "Aurangabad", "Dhanbad", "Amritsar",
  "Allahabad", "Guwahati", "Howrah", "Jabalpur", "Coimbatore", "Vijayawada", "Jodhpur",
  "Madurai", "Raipur", "Kota", "Chandigarh", "Gwalior", "Hubli-Dharwad", "Bareilly",
  "Moradabad", "Mysuru", "Tiruchirappalli", "Tirunelveli", "Noida", "Gurugram",
  "Dehradun", "Shimla", "Mangaluru", "Udaipur", "Bikaner", "Siliguri", "Imphal",
  "Shillong", "Aizawl", "Gangtok", "Itanagar", "Kohima", "Agartala",
];

// Common post office name suggestions
export const commonPostOffices = [
  "Head Post Office", "Sub Post Office", "Branch Post Office", "GPO",
];

// Common localities for autocomplete
export const commonLocalities = [
  "Gandhi Nagar", "Nehru Nagar", "Shanti Nagar", "Rajendra Nagar", "Laxmi Nagar",
  "Vikas Nagar", "Indira Nagar", "Subhash Nagar", "Patel Nagar", "Sector 1",
  "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Civil Lines", "Cantonment",
  "Station Road", "Old City", "New Colony", "Model Town", "Industrial Area",
  "Sadar Bazar", "Main Market", "Bank Colony", "Teachers Colony", "Railway Colony",
  "Adarsh Nagar", "Azad Nagar", "Jawahar Nagar", "Ashok Nagar", "Tilak Nagar",
  "Shivaji Nagar", "MG Road", "GT Road", "Ring Road", "Bypass Road",
];

// Common police station names
export const commonPoliceStations = [
  "Kotwali", "Sadar", "City", "Civil Lines", "Cantonment", "Industrial Area",
  "Railway", "Mahila Thana", "Cyber Crime", "Traffic", "Town", "Nagar",
  "Main", "Central", "East", "West", "North", "South",
];

// Pin codes mapped to state codes (sample)
export const statePincodeRanges: Record<string, { prefix: string; samples: string[] }> = {
  AN: { prefix: "744", samples: ["744101", "744102", "744103"] },
  AP: { prefix: "5", samples: ["500001", "520001", "530001", "515001", "522001", "518001"] },
  AR: { prefix: "79", samples: ["791001", "791111", "792001"] },
  AS: { prefix: "78", samples: ["781001", "782001", "783001", "784001", "785001"] },
  BR: { prefix: "8", samples: ["800001", "801001", "802001", "812001", "813001", "842001"] },
  CH: { prefix: "160", samples: ["160001", "160002", "160003", "160009", "160014"] },
  CG: { prefix: "49", samples: ["490001", "491001", "492001", "495001", "496001"] },
  DN: { prefix: "396", samples: ["396001", "396210", "396220"] },
  DL: { prefix: "110", samples: ["110001", "110002", "110003", "110006", "110011", "110025", "110044", "110085"] },
  GA: { prefix: "403", samples: ["403001", "403002", "403401", "403501", "403601"] },
  GJ: { prefix: "3", samples: ["380001", "360001", "390001", "370001", "395001", "382001"] },
  HR: { prefix: "1", samples: ["121001", "122001", "124001", "125001", "126001", "132001"] },
  HP: { prefix: "17", samples: ["171001", "172001", "173001", "175001", "176001"] },
  JK: { prefix: "18", samples: ["180001", "181001", "184001", "190001", "191001"] },
  JH: { prefix: "8", samples: ["826001", "827001", "828001", "831001", "834001"] },
  KA: { prefix: "5", samples: ["560001", "570001", "575001", "580001", "585001", "590001"] },
  KL: { prefix: "6", samples: ["670001", "680001", "682001", "686001", "690001", "695001"] },
  LA: { prefix: "194", samples: ["194101", "194201"] },
  LD: { prefix: "682", samples: ["682555", "682556"] },
  MP: { prefix: "4", samples: ["452001", "462001", "470001", "474001", "480001", "482001"] },
  MH: { prefix: "4", samples: ["400001", "410001", "411001", "416001", "431001", "440001"] },
  MN: { prefix: "795", samples: ["795001", "795002", "795003", "795004"] },
  ML: { prefix: "793", samples: ["793001", "793002", "793003", "793004"] },
  MZ: { prefix: "796", samples: ["796001", "796002", "796003"] },
  NL: { prefix: "797", samples: ["797001", "797002", "797003"] },
  OD: { prefix: "7", samples: ["751001", "752001", "753001", "756001", "760001", "769001"] },
  PY: { prefix: "605", samples: ["605001", "605002", "605003"] },
  PB: { prefix: "1", samples: ["140001", "141001", "143001", "144001", "147001", "148001"] },
  RJ: { prefix: "3", samples: ["302001", "303001", "305001", "311001", "313001", "324001", "334001", "342001"] },
  SK: { prefix: "737", samples: ["737101", "737102", "737103"] },
  TN: { prefix: "6", samples: ["600001", "620001", "625001", "630001", "636001", "641001"] },
  TS: { prefix: "5", samples: ["500001", "501001", "503001", "505001", "506001"] },
  TR: { prefix: "799", samples: ["799001", "799002", "799003"] },
  UP: { prefix: "2", samples: ["201001", "208001", "211001", "221001", "226001", "231001", "250001", "282001"] },
  UK: { prefix: "2", samples: ["244001", "246001", "248001", "249001", "263001"] },
  WB: { prefix: "7", samples: ["700001", "711001", "712001", "721001", "731001", "734001"] },
};

/** Check if a 6-digit pincode belongs to the given state (by name or code). */
export function isPincodeValidForState(pin: string, stateNameOrCode: string): boolean {
  if (!pin || pin.length !== 6) return false;
  const state = indianStates.find((s) => s.name === stateNameOrCode || s.code === stateNameOrCode);
  if (!state) return true;
  const range = statePincodeRanges[state.code];
  if (!range?.samples?.length) return true;
  const allowedPrefixes = new Set(range.samples.map((s) => s.slice(0, 2)));
  return allowedPrefixes.has(pin.slice(0, 2));
}

// Get cities for a state
export const getCitiesForState = (stateCode: string): string[] => {
  const stateCityMap: Record<string, string[]> = {
    AN: ["Port Blair", "Havelock Island", "Neil Island", "Car Nicobar"],
    AP: ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool", "Tirupati", "Rajahmundry", "Kakinada", "Eluru", "Anantapur", "Kadapa"],
    AR: ["Itanagar", "Naharlagun", "Pasighat", "Tawang", "Ziro", "Along", "Tezu"],
    AS: ["Guwahati", "Dibrugarh", "Jorhat", "Silchar", "Nagaon", "Tinsukia", "Tezpur", "Barpeta"],
    BR: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Darbhanga", "Purnia", "Begusarai", "Araria"],
    CH: ["Chandigarh"],
    CG: ["Raipur", "Bhilai", "Bilaspur", "Durg", "Korba", "Rajnandgaon", "Jagdalpur"],
    DN: ["Silvassa", "Daman", "Diu"],
    DL: ["New Delhi", "Dwarka", "Rohini", "Shahdara", "Saket", "Pitampura", "Janakpuri", "Lajpat Nagar"],
    GA: ["Panaji", "Margao", "Mapusa", "Vasco da Gama", "Ponda"],
    GJ: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Jamnagar", "Gandhinagar", "Junagadh", "Anand", "Kutch"],
    HR: ["Gurugram", "Faridabad", "Panipat", "Ambala", "Karnal", "Sonipat", "Hisar", "Rohtak", "Bhiwani"],
    HP: ["Shimla", "Manali", "Dharamshala", "Kullu", "Solan", "Mandi", "Una", "Hamirpur"],
    JK: ["Srinagar", "Jammu", "Anantnag", "Baramulla", "Udhampur", "Kathua", "Rajouri"],
    JH: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Hazaribagh", "Giridih", "Dumka"],
    KA: ["Bengaluru", "Mysuru", "Hubli", "Mangaluru", "Belagavi", "Shivamogga", "Tumakuru", "Davangere", "Udupi", "Hassan"],
    KL: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam", "Kannur", "Alappuzha", "Palakkad", "Malappuram"],
    LA: ["Leh", "Kargil"],
    LD: ["Kavaratti", "Agatti", "Minicoy"],
    MP: ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain", "Sagar", "Rewa", "Satna"],
    MH: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad", "Solapur", "Kolhapur", "Thane", "Navi Mumbai"],
    MN: ["Imphal", "Thoubal", "Bishnupur", "Churachandpur"],
    ML: ["Shillong", "Tura", "Jowai", "Nongstoin"],
    MZ: ["Aizawl", "Lunglei", "Champhai", "Serchhip"],
    NL: ["Kohima", "Dimapur", "Mokokchung", "Tuensang", "Mon"],
    OD: ["Bhubaneswar", "Cuttack", "Rourkela", "Berhampur", "Sambalpur", "Puri", "Balasore"],
    PY: ["Puducherry", "Karaikal", "Mahe", "Yanam"],
    PB: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda", "Mohali", "Pathankot"],
    RJ: ["Jaipur", "Jodhpur", "Udaipur", "Kota", "Bikaner", "Ajmer", "Alwar"],
    SK: ["Gangtok", "Namchi", "Gyalshing", "Mangan"],
    TN: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli", "Erode", "Vellore", "Thanjavur"],
    TS: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Khammam", "Nalgonda"],
    TR: ["Agartala", "Udaipur", "Dharmanagar", "Kailashahar"],
    UP: ["Lucknow", "Noida", "Ghaziabad", "Kanpur", "Agra", "Varanasi", "Allahabad", "Meerut", "Bareilly", "Gorakhpur", "Aligarh", "Moradabad"],
    UK: ["Dehradun", "Haridwar", "Rishikesh", "Nainital", "Almora", "Mussoorie", "Roorkee"],
    WB: ["Kolkata", "Howrah", "Siliguri", "Durgapur", "Bardhaman", "Darjeeling", "Malda", "Asansol"],
  };
  return stateCityMap[stateCode] || [];
};
